<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="4" total="12" passed="0" failed="8" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-04-28T20:17:24 IST" name="Suite" finished-at="2022-04-28T20:18:54 IST" duration-ms="89931">
    <groups>
    </groups>
    <test started-at="2022-04-28T20:17:24 IST" name="Test" finished-at="2022-04-28T20:18:00 IST" duration-ms="36482">
      <class name="POMProject.Script.LoginTest">
        <test-method signature="invalidUserNamenInvalidPassword()[pri:0, instance:POMProject.Script.LoginTest@25084a1e]" started-at="2022-04-28T20:17:58 IST" name="invalidUserNamenInvalidPassword" finished-at="2022-04-28T20:17:58 IST" duration-ms="96" status="FAIL">
          <exception class="java.lang.IncompatibleClassChangeError">
            <message>
              <![CDATA[Found interface org.apache.poi.util.POILogger, but class was expected]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:186)
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:173)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
at org.apache.poi.openxml4j.util.ZipSecureFile.addThreshold(ZipSecureFile.java:173)
at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:213)
at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:98)
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:295)
at POMProject.utilities.ExcelUtilities.excelStringFinder(ExcelUtilities.java:19)
at POMProject.Script.LoginTest.invalidUserNamenInvalidPassword(LoginTest.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IncompatibleClassChangeError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUserNamenInvalidPassword -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:POMProject.Script.LoginTest@25084a1e]" started-at="2022-04-28T20:17:58 IST" name="afterMethod" finished-at="2022-04-28T20:17:58 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="invalidUserNamenValidPassword()[pri:1, instance:POMProject.Script.LoginTest@25084a1e]" started-at="2022-04-28T20:17:58 IST" name="invalidUserNamenValidPassword" finished-at="2022-04-28T20:17:58 IST" duration-ms="3" status="FAIL">
          <exception class="java.lang.IncompatibleClassChangeError">
            <message>
              <![CDATA[Found interface org.apache.poi.util.POILogger, but class was expected]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:186)
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:173)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
at org.apache.poi.openxml4j.util.ZipSecureFile.addThreshold(ZipSecureFile.java:173)
at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:213)
at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:98)
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:295)
at POMProject.utilities.ExcelUtilities.excelStringFinder(ExcelUtilities.java:19)
at POMProject.Script.LoginTest.invalidUserNamenValidPassword(LoginTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IncompatibleClassChangeError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUserNamenValidPassword -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:POMProject.Script.LoginTest@25084a1e]" started-at="2022-04-28T20:17:58 IST" name="afterMethod" finished-at="2022-04-28T20:17:58 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="validUserNamenInvalidPassword()[pri:2, instance:POMProject.Script.LoginTest@25084a1e]" started-at="2022-04-28T20:17:58 IST" name="validUserNamenInvalidPassword" finished-at="2022-04-28T20:17:58 IST" duration-ms="4" status="FAIL">
          <exception class="java.lang.IncompatibleClassChangeError">
            <message>
              <![CDATA[Found interface org.apache.poi.util.POILogger, but class was expected]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:186)
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:173)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
at org.apache.poi.openxml4j.util.ZipSecureFile.addThreshold(ZipSecureFile.java:173)
at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:213)
at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:98)
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:295)
at POMProject.utilities.ExcelUtilities.excelStringFinder(ExcelUtilities.java:19)
at POMProject.Script.LoginTest.validUserNamenInvalidPassword(LoginTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IncompatibleClassChangeError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserNamenInvalidPassword -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:POMProject.Script.LoginTest@25084a1e]" started-at="2022-04-28T20:17:58 IST" name="afterMethod" finished-at="2022-04-28T20:17:58 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="ValidUserNamenValidPassword()[pri:3, instance:POMProject.Script.LoginTest@25084a1e]" started-at="2022-04-28T20:17:58 IST" name="ValidUserNamenValidPassword" finished-at="2022-04-28T20:17:58 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.IncompatibleClassChangeError">
            <message>
              <![CDATA[Found interface org.apache.poi.util.POILogger, but class was expected]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:186)
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:173)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
at org.apache.poi.openxml4j.util.ZipSecureFile.addThreshold(ZipSecureFile.java:173)
at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:213)
at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:98)
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:295)
at POMProject.utilities.ExcelUtilities.excelStringFinder(ExcelUtilities.java:19)
at POMProject.Script.LoginTest.ValidUserNamenValidPassword(LoginTest.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IncompatibleClassChangeError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidUserNamenValidPassword -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:POMProject.Script.LoginTest@25084a1e]" started-at="2022-04-28T20:17:58 IST" name="afterMethod" finished-at="2022-04-28T20:17:58 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- POMProject.Script.LoginTest -->
      <class name="POMProject.Script.LoginBase">
        <test-method is-config="true" signature="beforeTest(java.lang.String)[pri:0, instance:POMProject.Script.LoginBase@63a12c68]" started-at="2022-04-28T20:17:24 IST" name="beforeTest" finished-at="2022-04-28T20:17:58 IST" duration-ms="34071" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:POMProject.Script.LoginBase@63a12c68]" started-at="2022-04-28T20:17:58 IST" name="afterTest" finished-at="2022-04-28T20:18:00 IST" duration-ms="2223" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- POMProject.Script.LoginBase -->
    </test> <!-- Test -->
    <test started-at="2022-04-28T20:18:01 IST" name="Test1" finished-at="2022-04-28T20:18:54 IST" duration-ms="53375">
      <class name="POMProject.Script.LoginTest">
        <test-method signature="invalidUserNamenInvalidPassword()[pri:0, instance:POMProject.Script.LoginTest@7c711375]" started-at="2022-04-28T20:18:53 IST" name="invalidUserNamenInvalidPassword" finished-at="2022-04-28T20:18:53 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.IncompatibleClassChangeError">
            <message>
              <![CDATA[Found interface org.apache.poi.util.POILogger, but class was expected]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:186)
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:173)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
at org.apache.poi.openxml4j.util.ZipSecureFile.addThreshold(ZipSecureFile.java:173)
at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:213)
at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:98)
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:295)
at POMProject.utilities.ExcelUtilities.excelStringFinder(ExcelUtilities.java:19)
at POMProject.Script.LoginTest.invalidUserNamenInvalidPassword(LoginTest.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IncompatibleClassChangeError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUserNamenInvalidPassword -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:POMProject.Script.LoginTest@7c711375]" started-at="2022-04-28T20:18:53 IST" name="afterMethod" finished-at="2022-04-28T20:18:53 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="invalidUserNamenValidPassword()[pri:1, instance:POMProject.Script.LoginTest@7c711375]" started-at="2022-04-28T20:18:53 IST" name="invalidUserNamenValidPassword" finished-at="2022-04-28T20:18:53 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.IncompatibleClassChangeError">
            <message>
              <![CDATA[Found interface org.apache.poi.util.POILogger, but class was expected]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:186)
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:173)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
at org.apache.poi.openxml4j.util.ZipSecureFile.addThreshold(ZipSecureFile.java:173)
at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:213)
at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:98)
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:295)
at POMProject.utilities.ExcelUtilities.excelStringFinder(ExcelUtilities.java:19)
at POMProject.Script.LoginTest.invalidUserNamenValidPassword(LoginTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IncompatibleClassChangeError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUserNamenValidPassword -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:POMProject.Script.LoginTest@7c711375]" started-at="2022-04-28T20:18:53 IST" name="afterMethod" finished-at="2022-04-28T20:18:53 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="validUserNamenInvalidPassword()[pri:2, instance:POMProject.Script.LoginTest@7c711375]" started-at="2022-04-28T20:18:53 IST" name="validUserNamenInvalidPassword" finished-at="2022-04-28T20:18:53 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.IncompatibleClassChangeError">
            <message>
              <![CDATA[Found interface org.apache.poi.util.POILogger, but class was expected]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:186)
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:173)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
at org.apache.poi.openxml4j.util.ZipSecureFile.addThreshold(ZipSecureFile.java:173)
at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:213)
at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:98)
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:295)
at POMProject.utilities.ExcelUtilities.excelStringFinder(ExcelUtilities.java:19)
at POMProject.Script.LoginTest.validUserNamenInvalidPassword(LoginTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IncompatibleClassChangeError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserNamenInvalidPassword -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:POMProject.Script.LoginTest@7c711375]" started-at="2022-04-28T20:18:53 IST" name="afterMethod" finished-at="2022-04-28T20:18:53 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="ValidUserNamenValidPassword()[pri:3, instance:POMProject.Script.LoginTest@7c711375]" started-at="2022-04-28T20:18:53 IST" name="ValidUserNamenValidPassword" finished-at="2022-04-28T20:18:53 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.IncompatibleClassChangeError">
            <message>
              <![CDATA[Found interface org.apache.poi.util.POILogger, but class was expected]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:186)
at org.apache.poi.openxml4j.util.ZipSecureFile$1.run(ZipSecureFile.java:173)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
at org.apache.poi.openxml4j.util.ZipSecureFile.addThreshold(ZipSecureFile.java:173)
at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:213)
at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:98)
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:324)
at org.apache.poi.util.PackageHelper.open(PackageHelper.java:37)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:295)
at POMProject.utilities.ExcelUtilities.excelStringFinder(ExcelUtilities.java:19)
at POMProject.Script.LoginTest.ValidUserNamenValidPassword(LoginTest.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IncompatibleClassChangeError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidUserNamenValidPassword -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:POMProject.Script.LoginTest@7c711375]" started-at="2022-04-28T20:18:53 IST" name="afterMethod" finished-at="2022-04-28T20:18:53 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- POMProject.Script.LoginTest -->
      <class name="POMProject.Script.LoginBase">
        <test-method is-config="true" signature="beforeTest(java.lang.String)[pri:0, instance:POMProject.Script.LoginBase@54bff557]" started-at="2022-04-28T20:18:01 IST" name="beforeTest" finished-at="2022-04-28T20:18:53 IST" duration-ms="52490" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:POMProject.Script.LoginBase@54bff557]" started-at="2022-04-28T20:18:53 IST" name="afterTest" finished-at="2022-04-28T20:18:54 IST" duration-ms="870" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- POMProject.Script.LoginBase -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
